### ISSUE TITLE
Add properly rebar support

### ISSUE THREAD

**Issue by liveforeverx** [travelping/eradius#8]
Eradius should be possible to build with rebar

**Comment by surik** [comment]
Now it is possible to build eradius with `rebar2` but not possible to build with `rebar3` because of dictionary plugin.
For supporting rebar3 we need to write own dictionary plugin based on `rebar_plugins/eradius_compile_dicts_plugin.erl` source code. Also, this plugin should be separated from `eradius` code and placed to hex(or github) because `rebar3` can't use local plugins.

**Comment by surik** [comment]
Now, `rebar` and `rebar3` are supported. I'm going to close it.
